version: "3.9"

services:
  crawler:
    build:
      dockerfile: crawler.Dockerfile
    image: ghcr.io/lmullen/cchc-crawler:main
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 3
      window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  itemmd:
    build:
      dockerfile: itemmd.Dockerfile
    image: ghcr.io/lmullen/cchc-itemmd:main
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 3
      window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  qftext:
    build:
      dockerfile: qftext.Dockerfile
    image: ghcr.io/lmullen/cchc-qftext:main
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 3
      window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  predictor:
    build:
      dockerfile: predictor.Dockerfile
    image: ghcr.io/lmullen/cchc-predictor:main
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
      - CCHC_MQSTR
      - PASSWORD=guest
    restart_policy:
      condition: on-failure
      delay: 15s
      max_attempts: 3
      window: 120s
    deploy:
      mode: replicated
      replicas: 2
    network_mode: "host"
    # volumes:
    #   - ./potential-matches/:/tmp/potential/
