version: "3.9"

services:
  queue:
    image: rabbitmq:3-management
    container_name: "cchc-queue"
    hostname: "cchc-rabbitmq"
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - queue-data:/var/lib/rabbitmq/
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    # network_mode: "host"

  crawler:
    build:
      dockerfile: crawler.Dockerfile
    image: ghcr.io/lmullen/cchc-crawler:main
    container_name: "cchc-crawler"
    restart: unless-stopped
    environment:
      - CCHC_DBHOST
      - CCHC_DBPORT
      - CCHC_DBUSER
      - CCHC_DBPASS
      - CCHC_DBNAME
      - CCHC_LOGLEVEL
      - CCHC_QHOST
      - CCHC_QPORT
      - CCHC_QUSER
      - CCHC_QPASS
    depends_on:
      - "queue"
    network_mode: "host"
    volumes:
      - crawler-build-cache:/root/.cache/go-build

  itemmd:
    build:
      dockerfile: itemmd.Dockerfile
    image: ghcr.io/lmullen/cchc-itemmd:main
    container_name: "cchc-itemmd"
    restart: unless-stopped
    environment:
      - CCHC_DBHOST
      - CCHC_DBPORT
      - CCHC_DBUSER
      - CCHC_DBPASS
      - CCHC_DBNAME
      - CCHC_LOGLEVEL
      - CCHC_QHOST
      - CCHC_QPORT
      - CCHC_QUSER
      - CCHC_QPASS
    depends_on:
      - "queue"
    network_mode: "host"
    volumes:
      - itemmd-build-cache:/root/.cache/go-build

  predictor:
    build:
      dockerfile: predictor.Dockerfile
    image: ghcr.io/lmullen/cchc-predictor:main
    container_name: "cchc-predictor"
    restart: unless-stopped
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
      - PASSWORD=guest
    ports:
      - 8787:8787
    depends_on:
      - "queue"
    network_mode: "host"

volumes:
  queue-data:
  crawler-build-cache:
  itemmd-build-cache:
