version: "3.9"

services:
  crawler:
    build:
      dockerfile: crawler.Dockerfile
    image: ghcr.io/lmullen/cchc-crawler:main
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  itemmd:
    build:
      dockerfile: itemmd.Dockerfile
    image: ghcr.io/lmullen/cchc-itemmd:main
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  language-detector:
    build:
      dockerfile: language-detector.Dockerfile
    image: ghcr.io/lmullen/cchc-language-detector:main
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    network_mode: "host"

  predictor:
    build:
      dockerfile: predictor.Dockerfile
    image: ghcr.io/lmullen/cchc-predictor:main
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
      - PASSWORD=guest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    network_mode: "host"
