version: "3.9"

services:
  crawler:
    profiles:
      - api
    build:
      dockerfile: crawler.Dockerfile
    image: ghcr.io/lmullen/cchc-crawler:${CCHC_VERSION:-release}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  itemmd:
    profiles:
      - api
    build:
      dockerfile: itemmd.Dockerfile
    image: ghcr.io/lmullen/cchc-itemmd:${CCHC_VERSION:-release}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      - CCHC_DBSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  language-detector:
    profiles:
      - language
    build:
      dockerfile: language-detector.Dockerfile
    image: ghcr.io/lmullen/cchc-language-detector:${CCHC_VERSION:-release}
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    network_mode: "host"

  predictor:
    profiles:
      - quotations
    build:
      dockerfile: predictor.Dockerfile
    image: ghcr.io/lmullen/cchc-predictor:${CCHC_VERSION:-release}
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
      - PASSWORD=guest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    network_mode: "host"

  ctrl:
    profiles:
      - ctrl
    deploy:
      restart_policy:
        condition: none
    build:
      dockerfile: cchc-ctrl.Dockerfile
    image: ghcr.io/lmullen/cchc-ctrl:${CCHC_VERSION:-release}
    environment:
      - CCHC_DBSTR
      - CCHC_LOGLEVEL
    network_mode: "host"

  db:
    profiles:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${CCHC_DB_PASSWORD:-cchcdbpass}
      POSTGRES_USER: cchc
      POSTGRES_DB: cchc
    ports:
      - 5433:5432
    volumes:
      - cchc-dbdata:/var/lib/postgresql/data

  adminer:
    profiles:
      - db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    image: adminer
    ports:
      - 8888:8080

volumes: 
  cchc-dbdata:
