version: "3.9"

services:
  crawler:
    build:
      dockerfile: crawler.Dockerfile
    image: ghcr.io/lmullen/cchc-crawler:main
    restart: unless-stopped
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"
    volumes:
      - go-build-cache:/root/.cache/go-build

  itemmd:
    build:
      dockerfile: itemmd.Dockerfile
    image: ghcr.io/lmullen/cchc-itemmd:main
    restart: unless-stopped
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"
    volumes:
      - go-build-cache:/root/.cache/go-build

  qftext:
    build:
      dockerfile: qftext.Dockerfile
    image: ghcr.io/lmullen/cchc-qftext:main
    restart: unless-stopped
    environment:
      - CCHC_DBSTR
      - CCHC_MQSTR
      - CCHC_LOGLEVEL
    network_mode: "host"
    volumes:
      - go-build-cache:/root/.cache/go-build

  predictor:
    build:
      dockerfile: predictor.Dockerfile
    image: ghcr.io/lmullen/cchc-predictor:main
    restart: unless-stopped
    environment:
      - CCHC_LOGLEVEL
      - CCHC_DBSTR
      - CCHC_MQSTR
      - PASSWORD=guest
    deploy:
      mode: replicated
      replicas: 2
    network_mode: "host"
    # volumes:
    #   - ./potential-matches/:/tmp/potential/

volumes:
  go-build-cache:
