package main

import "time"

var remove = []string{"more_like_this", "related_items", "cite_this"}

// Item represents an item-level object returned from the API. Many more fields
// are returned and will be stored in the database as a JSONB field, but these
// are the ones that will be serialized to regular database fields.
type Item struct {
	ItemDetails struct {
		Version      int64     `json:"_version_"`
		Date         string    `json:"date"`
		Digitized    bool      `json:"digitized"`
		HasSegments  bool      `json:"hassegments"`
		ID           string    `json:"id"`
		Language     []string  `json:"language"`
		OnlineFormat []string  `json:"online_format"`
		Subjects     []string  `json:"subject_headings"`
		Timestamp    time.Time `json:"timestamp"`
		Title        string    `json:"title"`
		URL          string    `json:"url"`
	} `json:"item"`
	Resources []struct {
		Caption string `json:"caption"`
		Files   [][]struct {
			Height   int    `json:"height"`
			Levels   int    `json:"levels"`
			Mimetype string `json:"mimetype"`
			Size     int    `json:"size"`
			URL      string `json:"url"`
			Width    int    `json:"width"`
			Fulltext string `json:"fulltext,omitempty"`
			Use      string `json:"use,omitempty"`
		} `json:"files"`
		FulltextFile string `json:"fulltext_file"`
		Image        string `json:"image"`
		URL          string `json:"url"`
	} `json:"resources"`
	Timestamp int64 `json:"timestamp"`
}

type AutoGenerated struct {
	ArticlesAndEssays interface{} `json:"articles_and_essays"`
	CalendarURL       string      `json:"calendar_url"`
	CiteThis          struct {
		Apa     string `json:"apa"`
		Chicago string `json:"chicago"`
		Mla     string `json:"mla"`
	} `json:"cite_this"`
	Item struct {
		Version           int64         `json:"_version_"`
		AccessRestricted  bool          `json:"access_restricted"`
		Aka               []string      `json:"aka"`
		Batch             []string      `json:"batch"`
		CallNumber        []string      `json:"call_number"`
		Campaigns         []interface{} `json:"campaigns"`
		CompositeLocation []string      `json:"composite_location"`
		ContributorNames  []string      `json:"contributor_names"`
		Contributors      []struct {
			LibraryOfCongressWashingtonDc string `json:"library of congress, washington, dc"`
		} `json:"contributors"`
		CreatedPublished []string `json:"created_published"`
		Date             string   `json:"date"`
		DateIssued       string   `json:"date_issued"`
		Dates            []struct {
			Num1899 string `json:"1899"`
		} `json:"dates"`
		DatesOfPublication string    `json:"dates_of_publication"`
		Description        []string  `json:"description"`
		Digitized          bool      `json:"digitized"`
		DigitizedLabel     string    `json:"digitized_label"`
		DisplayOffsite     bool      `json:"display_offsite"`
		ExtractTimestamp   time.Time `json:"extract_timestamp"`
		ExtractUrls        []string  `json:"extract_urls"`
		Format             []struct {
			Newspaper string `json:"newspaper"`
		} `json:"format"`
		Genre       []string `json:"genre"`
		Group       []string `json:"group"`
		Hassegments bool     `json:"hassegments"`
		ID          string   `json:"id"`
		ImageURL    []string `json:"image_url"`
		Index       int      `json:"index"`
		Item        struct {
			Batch                          []string `json:"batch"`
			CallNumber                     []string `json:"call_number"`
			ContributorNames               []string `json:"contributor_names"`
			Contributors                   []string `json:"contributors"`
			CreatedPublished               []string `json:"created_published"`
			Date                           string   `json:"date"`
			DateIssued                     string   `json:"date_issued"`
			Dates                          []string `json:"dates"`
			DigitizedLabel                 string   `json:"digitized_label"`
			Format                         []string `json:"format"`
			Genre                          []string `json:"genre"`
			Language                       []string `json:"language"`
			LibraryOfCongressControlNumber string   `json:"library_of_congress_control_number"`
			Location                       []string `json:"location"`
			Medium                         string   `json:"medium"`
			NewspaperTitle                 []string `json:"newspaper_title"`
			Notes                          []string `json:"notes"`
			OtherFormats                   []string `json:"other_formats"`
			OtherTitle                     []string `json:"other_title"`
			PlaceOfPublication             string   `json:"place_of_publication"`
			RawLccn                        string   `json:"raw_lccn"`
			SourceGroup                    string   `json:"source_group"`
			Subjects                       []string `json:"subjects"`
			Title                          string   `json:"title"`
		} `json:"item"`
		ItemType  string   `json:"item_type"`
		Language  []string `json:"language"`
		Languages []struct {
			English string `json:"english"`
		} `json:"languages"`
		LibraryOfCongressControlNumber string   `json:"library_of_congress_control_number"`
		Location                       []string `json:"location"`
		LocationCity                   []string `json:"location_city"`
		LocationCountry                []string `json:"location_country"`
		LocationCounty                 []string `json:"location_county"`
		LocationState                  []string `json:"location_state"`
		Locations                      []struct {
			NewYork       string `json:"new york,omitempty"`
			NewYorkCity   string `json:"new york city,omitempty"`
			NewYorkCounty string `json:"new york county,omitempty"`
			UnitedStates  string `json:"united states,omitempty"`
		} `json:"locations"`
		LocationsCity []struct {
			NewYork string `json:"new york"`
		} `json:"locations_city"`
		LocationsCountry []struct {
			UnitedStates string `json:"united states"`
		} `json:"locations_country"`
		LocationsCounty []struct {
			NewYork string `json:"new york"`
		} `json:"locations_county"`
		LocationsState []struct {
			NewYork string `json:"new york"`
		} `json:"locations_state"`
		Medium         string   `json:"medium"`
		Method         string   `json:"method"`
		MimeType       []string `json:"mime_type"`
		NewspaperTitle []string `json:"newspaper_title"`
		Notes          []string `json:"notes"`
		Number         []string `json:"number"`
		NumberEdition  []string `json:"number_edition"`
		NumberLccn     []string `json:"number_lccn"`
		NumericShelfID int      `json:"numeric_shelf_id"`
		OnlineFormat   []string `json:"online_format"`
		OriginalFormat []string `json:"original_format"`
		OtherFormats   []struct {
			Label string `json:"label"`
			Link  string `json:"link"`
		} `json:"other_formats"`
		OtherTitle []string `json:"other_title"`
		Partof     []struct {
			Count int    `json:"count"`
			Title string `json:"title"`
			URL   string `json:"url"`
		} `json:"partof"`
		PartofCollection     []string `json:"partof_collection"`
		PartofDivision       []string `json:"partof_division"`
		PartofTitle          []string `json:"partof_title"`
		PlaceOfPublication   string   `json:"place_of_publication"`
		PublicationFrequency []string `json:"publication_frequency"`
		RawLccn              string   `json:"raw_lccn"`
		Resources            []struct {
			Files           int    `json:"files"`
			Image           string `json:"image"`
			URL             string `json:"url"`
			WordCoordinates string `json:"word_coordinates"`
		} `json:"resources"`
		Rights          []string `json:"rights"`
		Score           float64  `json:"score"`
		ShelfID         string   `json:"shelf_id"`
		Site            []string `json:"site"`
		SourceGroup     string   `json:"source_group"`
		Subject         []string `json:"subject"`
		SubjectHeadings []string `json:"subject_headings"`
		Subjects        []struct {
			NewYork         string `json:"new york,omitempty"`
			NewYorkNY       string `json:"new york (n.y.),omitempty"`
			NewYorkState    string `json:"new york (state),omitempty"`
			NewYorkCounty   string `json:"new york county,omitempty"`
			NewYorkCountyNY string `json:"new york county (n.y.),omitempty"`
			Newspapers      string `json:"newspapers,omitempty"`
			UnitedStates    string `json:"united states,omitempty"`
		} `json:"subjects"`
		Timestamp time.Time `json:"timestamp"`
		Title     string    `json:"title"`
		Type      []string  `json:"type"`
		URL       string    `json:"url"`
	} `json:"item"`
	Locations interface{} `json:"locations"`
	Method    string      `json:"method"`
	NextIssue string      `json:"next_issue"`
	Options   struct {
		AccessGroup        []string      `json:"access_group"`
		AccessGroupRaw     string        `json:"access_group_raw"`
		All                interface{}   `json:"all"`
		APIVersion         string        `json:"api_version"`
		AppContext         interface{}   `json:"app_context"`
		ApplicationVersion string        `json:"application_version"`
		Attribute          interface{}   `json:"attribute"`
		Attribute          string        `json:"attribute!"`
		AttributeMap       interface{}   `json:"attribute_map"`
		CacheTags          []string      `json:"cache_tags"`
		Callback           interface{}   `json:"callback"`
		Clip               interface{}   `json:"clip"`
		ClipImageWidth     interface{}   `json:"clip_image_width"`
		ClipRotation       interface{}   `json:"clip_rotation"`
		ContentFilter      interface{}   `json:"content_filter"`
		ContentReplacement string        `json:"content_replacement"`
		Count              interface{}   `json:"count"`
		Dates              interface{}   `json:"dates"`
		DefaultCount       int           `json:"default_count"`
		Delimiter          interface{}   `json:"delimiter"`
		DigitalID          interface{}   `json:"digital_id"`
		DisplayLevel       interface{}   `json:"display_level"`
		Distance           interface{}   `json:"distance"`
		DownloadOption     interface{}   `json:"downloadOption"`
		Duration           float64       `json:"duration"`
		Embed              []interface{} `json:"embed"`
		Embed              []interface{} `json:"embed!"`
		ExcludeTerms       interface{}   `json:"excludeTerms"`
		FacetLimits        string        `json:"facetLimits"`
		FacetPrefix        interface{}   `json:"facetPrefix"`
		FacetCount         interface{}   `json:"facet_count"`
		FacetStyle         interface{}   `json:"facet_style"`
		Field              interface{}   `json:"field"`
		Format             string        `json:"format"`
		Host               string        `json:"host"`
		Ical               bool          `json:"ical"`
		ID                 string        `json:"id"`
		Iiif               bool          `json:"iiif"`
		Index              interface{}   `json:"index"`
		InputEncoding      string        `json:"inputEncoding"`
		IsPortal           interface{}   `json:"is_portal"`
		Item               interface{}   `json:"item"`
		Items              interface{}   `json:"items"`
		Keys               interface{}   `json:"keys"`
		Language           interface{}   `json:"language"`
		Latlong            interface{}   `json:"latlong"`
		Method             string        `json:"method"`
		NewSearch          interface{}   `json:"newSearch"`
		NewClipURL         bool          `json:"new_clip_url"`
		Onsite             bool          `json:"onsite"`
		Operator           interface{}   `json:"operator"`
		OutputEncoding     string        `json:"outputEncoding"`
		PageHasCampaign    bool          `json:"page_has_campaign"`
		PathInfo           string        `json:"path_info"`
		Port               string        `json:"port"`
		Proxypath          interface{}   `json:"proxypath"`
		QueryString        string        `json:"query_string"`
		RedirectProxy      bool          `json:"redirect_proxy"`
		RedirectToItem     interface{}   `json:"redirect_to_item"`
		Referer            interface{}   `json:"referer"`
		Region             string        `json:"region"`
		ReleaseID          int           `json:"release_id"`
		RequestParams      struct {
			At []string `json:"at!"`
			Fo []string `json:"fo"`
		} `json:"request_params"`
		RequestURL       string      `json:"request_url"`
		Resource         string      `json:"resource"`
		ResourceSequence interface{} `json:"resource_sequence"`
		Scheme           string      `json:"scheme"`
		SearchIn         interface{} `json:"searchIn"`
		SearchTerms      string      `json:"searchTerms"`
		Segments         interface{} `json:"segments"`
		SiteID           interface{} `json:"site_id"`
		SiteType         interface{} `json:"site_type"`
		SolrQuery        string      `json:"solrQuery"`
		SortBy           interface{} `json:"sortBy"`
		SortOrder        interface{} `json:"sortOrder"`
		StartPage        interface{} `json:"startPage"`
		Style            interface{} `json:"style"`
		Suggested        interface{} `json:"suggested"`
		Target           interface{} `json:"target"`
		Template         string      `json:"template"`
		Timestamp        float64     `json:"timestamp"`
		UnionFacets      string      `json:"unionFacets"`
		WebcastPermalink interface{} `json:"webcast_permalink"`
	} `json:"options"`
	PreviousIssue string `json:"previous_issue"`
	Resources     []struct {
		Files [][]struct {
			Height          int         `json:"height,omitempty"`
			Info            string      `json:"info,omitempty"`
			Mimetype        string      `json:"mimetype"`
			Size            int         `json:"size,omitempty"`
			URL             string      `json:"url,omitempty"`
			Use             string      `json:"use,omitempty"`
			Width           int         `json:"width,omitempty"`
			Levels          int         `json:"levels,omitempty"`
			Language        []string    `json:"language,omitempty"`
			ReelNumber      interface{} `json:"reel_number,omitempty"`
			SectionLabel    interface{} `json:"section_label,omitempty"`
			Title           string      `json:"title,omitempty"`
			FulltextService string      `json:"fulltext_service,omitempty"`
			WordCoordinates string      `json:"word_coordinates,omitempty"`
		} `json:"files"`
		Image           string `json:"image"`
		URL             string `json:"url"`
		WordCoordinates string `json:"word_coordinates"`
	} `json:"resources"`
	Timestamp int64  `json:"timestamp"`
	TitleURL  string `json:"title_url"`
}
