// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: grpcproof/document.proto

package grpcproof

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Document struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Sent *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent,proto3" json:"sent,omitempty"`
}

func (x *Document) Reset() {
	*x = Document{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproof_document_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproof_document_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_grpcproof_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Document) GetSent() *timestamppb.Timestamp {
	if x != nil {
		return x.Sent
	}
	return nil
}

type DocumentAcknowledgement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DocumentAcknowledgement) Reset() {
	*x = DocumentAcknowledgement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcproof_document_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DocumentAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentAcknowledgement) ProtoMessage() {}

func (x *DocumentAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproof_document_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentAcknowledgement.ProtoReflect.Descriptor instead.
func (*DocumentAcknowledgement) Descriptor() ([]byte, []int) {
	return file_grpcproof_document_proto_rawDescGZIP(), []int{1}
}

var File_grpcproof_document_proto protoreflect.FileDescriptor

var file_grpcproof_document_proto_rawDesc = []byte{
	0x0a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2f, 0x64, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x08, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2e, 0x0a, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x04, 0x73, 0x65, 0x6e, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x32, 0x5d, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x12, 0x4e, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x6f,
	0x66, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x1a, 0x23, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x2e, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x22,
	0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x6d, 0x75, 0x6c, 0x6c, 0x65, 0x6e, 0x2f, 0x63, 0x63, 0x68, 0x63, 0x2f, 0x73, 0x6b, 0x65,
	0x74, 0x63, 0x68, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_grpcproof_document_proto_rawDescOnce sync.Once
	file_grpcproof_document_proto_rawDescData = file_grpcproof_document_proto_rawDesc
)

func file_grpcproof_document_proto_rawDescGZIP() []byte {
	file_grpcproof_document_proto_rawDescOnce.Do(func() {
		file_grpcproof_document_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcproof_document_proto_rawDescData)
	})
	return file_grpcproof_document_proto_rawDescData
}

var file_grpcproof_document_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpcproof_document_proto_goTypes = []interface{}{
	(*Document)(nil),                // 0: grpc_proof.Document
	(*DocumentAcknowledgement)(nil), // 1: grpc_proof.DocumentAcknowledgement
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
}
var file_grpcproof_document_proto_depIdxs = []int32{
	2, // 0: grpc_proof.Document.sent:type_name -> google.protobuf.Timestamp
	0, // 1: grpc_proof.Transmitter.ProcessDocument:input_type -> grpc_proof.Document
	1, // 2: grpc_proof.Transmitter.ProcessDocument:output_type -> grpc_proof.DocumentAcknowledgement
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpcproof_document_proto_init() }
func file_grpcproof_document_proto_init() {
	if File_grpcproof_document_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcproof_document_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Document); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcproof_document_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DocumentAcknowledgement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcproof_document_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproof_document_proto_goTypes,
		DependencyIndexes: file_grpcproof_document_proto_depIdxs,
		MessageInfos:      file_grpcproof_document_proto_msgTypes,
	}.Build()
	File_grpcproof_document_proto = out.File
	file_grpcproof_document_proto_rawDesc = nil
	file_grpcproof_document_proto_goTypes = nil
	file_grpcproof_document_proto_depIdxs = nil
}
